module Evergreen.Migrate.V7 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V1.Chars
import Evergreen.V1.Types
import Evergreen.V7.Chars
import Evergreen.V7.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V7.Types.FrontendModel Evergreen.V7.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V7.Types.BackendModel Evergreen.V7.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V7.Types.FrontendMsg Evergreen.V7.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V7.Types.ToBackend Evergreen.V7.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V7.Types.BackendMsg Evergreen.V7.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V7.Types.ToFrontend Evergreen.V7.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Chars_Points : Evergreen.V1.Chars.Points -> Evergreen.V7.Chars.Points
migrate_Chars_Points old =
    case old of
        Evergreen.V1.Chars.Experience ->
            Evergreen.V7.Chars.Experience


migrate_Chars_PoolType : Evergreen.V1.Chars.PoolType -> Evergreen.V7.Chars.PoolType
migrate_Chars_PoolType old =
    case old of
        Evergreen.V1.Chars.Might ->
            Evergreen.V7.Chars.Might

        Evergreen.V1.Chars.Speed ->
            Evergreen.V7.Chars.Speed

        Evergreen.V1.Chars.Intellect ->
            Evergreen.V7.Chars.Intellect


migrate_Types_FrontendMsg : Evergreen.V1.Types.FrontendMsg -> Evergreen.V7.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V1.Types.UrlClicked p0 ->
            Evergreen.V7.Types.UrlClicked p0

        Evergreen.V1.Types.UrlChanged p0 ->
            Evergreen.V7.Types.UrlChanged p0

        Evergreen.V1.Types.OnRecklessSend p0 ->
            Evergreen.V7.Types.OnRecklessSend (p0 |> migrate_Types_ToBackend)

        Evergreen.V1.Types.OnSelectCharacter p0 ->
            Evergreen.V7.Types.OnSelectCharacter p0

        Evergreen.V1.Types.OnTextareaInput p0 ->
            Evergreen.V7.Types.OnTextareaInput p0


migrate_Types_ToBackend : Evergreen.V1.Types.ToBackend -> Evergreen.V7.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V1.Types.TbJson p0 ->
            Evergreen.V7.Types.TbJson p0

        Evergreen.V1.Types.TbRequestCharacters ->
            Evergreen.V7.Types.TbRequestCharacters

        Evergreen.V1.Types.TbName p0 p1 ->
            Evergreen.V7.Types.TbName p0 p1

        Evergreen.V1.Types.TbDeltaPoints p0 p1 p2 ->
            Evergreen.V7.Types.TbDeltaPoints p0 (p1 |> migrate_Chars_Points) p2

        Evergreen.V1.Types.TbDeltaPool p0 p1 p2 ->
            Evergreen.V7.Types.TbDeltaPool p0 (p1 |> migrate_Chars_PoolType) p2

        Evergreen.V1.Types.TbRecovery p0 p1 ->
            Evergreen.V7.Types.TbRecovery p0 p1

        Evergreen.V1.Types.TbRemoveCypher p0 p1 ->
            Evergreen.V7.Types.TbRemoveCypher p0 p1
